.github/workflows/deploy-storybook.yml

This builds the Storybook site and deploys to GitHub Pages.
It deploys from the `main` branch.
For this to work, 3 things will need to happen:
* [this PR](https://github.com/Greater-London-Authority/ldn-viz-tools/pull/16) needs to be merged so the site can build under Ubuntu (which uses a case-sensitive filesystem)
* the new monorepo structure needs to be merged from the `dev` branch into `main`
* `Source` needs to be set to `GitHub Actions` on the `Pages` tab of the repository settings:

Create GitHub Action deployment workflow

---

packages/ui/package.json
packages/ui/src/lib/tabSelector/TabSelector.stories.svelte
packages/ui/src/lib/tabSelector/TabSelector.svelte
packages/ui/src/lib/tabSelector/TabSelectorEntry.svelte

Creates tab-selector buttons with icons and labels:
See https://github.com/Greater-London-Authority/ldn-viz-tools/issues/14
This can be used for things other than tabs - it's really a RadioButtonGroup with support for icons.

Tab selector

---

package-lock.json
package.json
packages/charts/src/data/dataScatter.d.ts

I'm adding these because I had trouble getting things running yesterday afternoon. These commands were useful.
`packages/charts/src/data/dataScatter.d.ts` keeps getting created when building. I assume it is meant to be, but no one has yet to pushed it.

Add docs & clean package commands

---

packages/ui/src/lib/button/Button.svelte
packages/ui/src/lib/checkBox/CheckboxGroup.svelte
packages/ui/src/lib/dataDownloadButton/DataDownloadButton.stories.svelte
packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.stories.svelte
packages/ui/src/lib/radioButton/RadioButtonGroup.svelte

We shouldn't use `style` as the name of a prop - it should be reserved for applying CSS styling.

rename 'style' prop of button to 'variant'

---

apps/docs/.storybook/main.ts

This fixes #38: it makes the patterns used to find storybook stories mroe restrictive, so that they do not include the contents of `dist/` folders.

update storybook config to not throw errors after build

---

packages/ui/src/lib/checkBox/Checkbox.stories.svelte
packages/ui/src/lib/checkBox/CheckboxGroup.svelte

Previously, all checkboxes were initially unchecked, regardless of whether or not the `selectedOptions` prop was empty.

allow some checkboxes in a CheckboxGroup to be initially checked

---

.changeset/quick-llamas-share.md
packages/maps/package.json

Currently the style files in `themes/` aren't currently being published to npm; this PR should fix this.

export style files from map package

---

.changeset/breezy-otters-exercise.md
packages/ui/src/lib/checkBox/CheckboxGroup.svelte

This fixes the formatting of the "Clear All" button in the `CheckboxGroup` component - I accidentally mangled this when the `style` prop was renamed to `variant`.

fix formatting of button in CheckboxGroup

---

README.md

This adds images of badges to the README, showing the lnumber of the latest version of each package published to NPM.

Add badges to README showing package versions

---

.changeset/flat-phones-stare.md
packages/ui/src/lib/modal/Modal.stories.svelte
packages/ui/src/lib/modal/Modal.svelte

This adds a width prop to the modal component to control the max width of said component
**Why?**
This allows greater flexibility for things such as charts, videos, in modals where wider content is desirable
**How?**
Using the classnames utility the component now accepts a 'width' prop mapped from xs - 7xl + full tailwind classes
https://github.com/Greater-London-Authority/ldn-viz-tools/issues/77
no
storybook
storybook
n/a
- [y] Have you included changeset file?

Modal sizes

---

.changeset/thirty-boats-yell.md
packages/ui/src/lib/radioButtonSolid/RadioButtonSolid.stories.svelte
packages/ui/src/lib/radioButtonSolid/RadioButtonSolid.svelte

Currently:
* when there only 2 options, the buttons do not increase beyond their initial size of 1/3 of the total space, so the button group only occupies 2/3 of the space that it should
* when there are more than 3 options, a button with a longer label can end up larger than the others
This PR fixes the first problem by allowing the elements to grow, and fixes the second by setting the initial size to a value smaller than the eventual size of each button will be.

Fix sizes of radio buttons when number of options is not 3

---

.changeset/famou-pears-wink.md
README.md
packages/ui/src/lib/dataDownloadButton/DataDownloadButton.stories.svelte
packages/ui/src/lib/dataDownloadButton/DataDownloadButton.svelte

`DataDownloadButton` now accepts a prop defining a mapping from the names of fields in the provided data object, and the names that should be used in the downloaded file.

Rename columns for download

---

.changeset/abc-efg-hij.md
packages/maps/src/lib/map/Map.svelte
packages/maps/src/lib/map/MapApp.svelte

1. Fixed _MapApp_ not able to accommodate full width headers and footers.
2. Fixed _Map_ not hiding overflow caused by popups and tooltips on the map.
Also removed `id` from _Map_ as to accommodate multiple maps per page.
**Why?**
It broken.

Fix MapApp & Map layouts

---

.changeset/mon-tue-wed.md
packages/maps/src/lib/mapControlFullscreen/MapControlFullscreen.svelte
packages/maps/src/lib/mapControlGroup/MapControlGroup.stories.svelte
packages/maps/src/lib/mapControlGroup/MapControlGroup.svelte
packages/maps/src/lib/mapControlPan/MapControlPan.svelte
packages/maps/src/lib/mapControlRefresh/MapControlRefresh.svelte
packages/maps/src/lib/mapControlZoom/MapControlZoom.svelte

Fixes map controls interfering with map interactions.
**Why?**
Map control areas preventing panning and drawing on the map. Mostly only noticable on smaller laptops, e.g. surface pro etc.
**How?**
Disabled all pointer events in map controls and enable only at a fine grained level, i.e. applied pointer events to buttons directly rather than their containing elements to avoid padded and margin space from causing problems too.

Fix map controls divs interferring with map interactions

---

.changeset/hfuufh-ifie-eifie.md
packages/ui/src/lib/select/Select.stories.svelte
packages/ui/src/lib/select/Select.svelte

Add a `justValue` prop to the `Select` component that can be bound to.
The `value` prop is an object containing both the label and value of the selected item. This is inconvenient: 
Often the select sets a value that can also be updated by other interactions (for example, users might be able to select a borough by either using the select control or by clicking on a map). This is currently inconvenient to handle: we can't just bind a store to the `value` prop, since this is is an object containing both the label and value of the selected item, not just the value.
`svelte-select` provides a `justValue` prop, but it is read-only. This PR updates our wrapper around it (the `Select` component) to add a prop with the saem name that is writable.

Add justValue prop to Select component

---

.changeset/kgierif-dmiqwd-keiwie.md
packages/maps/package.json
packages/maps/src/lib/index.js

This fixes a warning from `vite-plugin-svelte`:
> The following packages have a svelte field in their package.json
> but no exports condition for svelte
See https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition
It does this by adding an exports condition (as for the other packages in the monorepo); MapLibre themes are now exported via index.js.
(see also https://github.com/Greater-London-Authority/ldn-viz-tools/commit/ae498d91358af59dd9faafcbe301a577e905ccb9)

Maps exports

---

.changeset/ghjghj_sdf_gfhio.md
packages/ui/src/lib/tooltip/Tooltip.svelte

Increases text size to `text-sm` for tooltip popup content.
**Why?**
Because current size is too small. Project clients requested it be increased for accessibility.
Stories.

Increase text size on tooltips

---

packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.stories.svelte
packages/ui/src/lib/input/Input.stories.svelte
packages/ui/src/lib/modal/Modal.stories.svelte
packages/ui/src/lib/nonIdealState/NonIdealState.stories.svelte
packages/ui/src/lib/placardButton/PlacardButton.stories.svelte
packages/ui/src/lib/spinners/Spinner.stories.svelte
packages/ui/src/lib/tabs/Tabs.stories.svelte
packages/ui/src/lib/tooltip/Tooltip.stories.svelte

This fixes storybook controls so that they update the components in defult stories.
For the controls to work, the default `<Story>` tag must be empty - it's contents should instead be set in the `<Template>`.

fix storybook controls so that they update component in default stories

---

.changeset/dscsdf_dda_swwd.md
packages/ui/src/lib/select/Select.svelte

This modifies `Select` so that it only has an `error` prop (rather than an `error` and `hasError` props)
This should address https://github.com/Greater-London-Authority/ldn-viz-tools/issues/295
@PaulioRandall, I don't know whether this touches on your planned changes to the `Select`

Remove `hasError` prop from `Select`

---

.changeset/fosff-ndsf-dad.md
packages/ui/src/lib/tooltip/Tooltip.svelte

This changes the alignment of the icon in the trigger of the `<Tooltip>` component.
Before:
After:

Align text and icon in tooltip trigger

---

packages/ui/src/lib/checkBox/Checkbox.stories.svelte
packages/ui/src/lib/checkBox/CheckboxGroup.stories.svelte
packages/ui/src/lib/radioButton/RadioButton.stories.svelte
packages/ui/src/lib/radioButton/RadioButtonGroup.stories.svelte

This separates the stories for the `Checkbox`/`CheckboxGroup` and `RadioButton`/`RadioButtonGroup` components.
It is intended to address https://github.com/Greater-London-Authority/ldn-viz-tools/issues/297

separate out stories for CheckboxGroup and RadioButtonGroup

---

packages/ui/src/lib/Introduction.mdx

Before:
After:
The suggestion of trying this came from https://github.com/storybookjs/storybook/discussions/22613#discussioncomment-8913396

fix formatting of markdown table in docs

---

.changeset/xxx_yyy_zzz.md
packages/ui/src/lib/checkBox/Checkbox.stories.svelte
packages/ui/src/lib/checkBox/Checkbox.svelte
packages/ui/src/lib/checkBox/CheckboxGroup.stories.svelte
packages/ui/src/lib/checkBox/CheckboxGroup.svelte
packages/ui/src/lib/utils/randomId.ts

Adds the `name` prop to `<Checkbox>` and `<CheckboxGroup>` options.
**Why?**
So they can be used within HTML forms.
Storybook.
Storybook.

Adds name prop to checkbox and checkbox group options

---

.changeset/mmm_nnn_bbb.md
packages/ui/src/lib/index.ts
packages/ui/src/lib/pageMetadata/PageMetadata.stories.svelte
packages/ui/src/lib/pageMetadata/PageMetadata.svelte

Adds a `<PageMetadata>` component that allows `<head>` tag information to be supplied on per-page basis. This includes but not limited to:
- title
- description
- custom favicon
- Open Graph properties
**Why?**
1. **Search Engine Optimization** (SEO): This information is used by search engines to index our digital services
2. **Preview links**: (OpenGraph) This information is used for preview links and text within search engine results (e.g. Google, DuckDuckGo, etc), social media platforms (e.g. X/Twitter, Facebook, etc), and communication platforms (e.g. MS Teams, WhatsApp, etc)
In various services but has been used in the following apps for 3-6 months:
- https://apps.london.gov.uk/wild-and-free
- https://apps.london.gov.uk/voter-id
**How …

Adds PageMetadata component

---

packages/ui/src/lib/colorLegends/ColorLegend.stories.svelte
packages/ui/src/lib/colorLegends/ColorLegendOrdinalHorizontal.stories.svelte
packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.stories.svelte
packages/ui/src/lib/input/Input.stories.svelte
packages/ui/src/lib/logos/Logos.stories.svelte
packages/ui/src/lib/placardButton/PlacardButton.stories.svelte
packages/ui/src/lib/radioButton/RadioButtonGroup.stories.svelte
packages/ui/src/lib/select/Select.stories.svelte
packages/ui/src/lib/spinners/Spinner.stories.svelte

This replaces the use of the deprecated `<Meta>` tag in some some stories with the now preferred approach of exporting a constant named  `meta`.
This updates the `.stories.svelte` files for UI components.

replace use of deprecated <Meta> tag in stories

---

.changeset/a_b_c.md
packages/ui/src/lib/checkBox/CheckboxGroup.svelte
packages/ui/src/lib/input/Input.stories.svelte
packages/ui/src/lib/input/Input.svelte
packages/ui/src/lib/input/InputWrapper.svelte
packages/ui/src/lib/select/Select.stories.svelte
packages/ui/src/lib/select/Select.svelte
packages/ui/src/lib/utils/randomId.ts

Updates: 
1. `Input` to allow textarea type.
2. `Input` to pass `$$restProps` to the input element to account for differences in properties for different input types.
3. `Input` to export the bindable input element value.
4. `Input` to allow a format value function to be passed that formats the value when unfocusing the input.
5. `InputWrapper` to allow tooltip hints in the label.
6. `Input` and `InputWrapper` with aria and accessibility attributes.
**Why?**
So the input is usable and accessible with HTML forms and multiple input types.
Storybook
Stroybook

Update Input and InputWrapper

---

packages/ui/src/lib/header/Header.stories.svelte
packages/ui/src/lib/header/Header.svelte
packages/ui/src/lib/header/HeaderItem.svelte
packages/ui/src/lib/header/HeaderRight.svelte
packages/ui/src/lib/header/HeaderTitle.svelte
packages/ui/src/lib/header/NavLink.svelte
packages/ui/src/lib/header/NavLinks.svelte

This adds some more docs for the header components.
It isn't perfect - for some reaosn Storybook doesn't seem to pick up `@component` comments for components with no props - but it is an improvement on the current docs.

[docs] add more docs for Header components

---

.changeset/check_box_each.md
packages/ui/src/lib/checkBox/CheckboxGroup.svelte

Adds a key to the `<CheckboxGroup>` each Svelte block.
**Why?**
Avoids the each block showing the same entry multiple times when the options are updated. This mostly affects hot reloading in dev mode but may affect a production app in cases where a `<CheckboxGroup>` options is updated via other options.
Temp storybook. Removed before commit.

Fix missing key in checkboxgroup each block

---

.changeset/hseu_nsne_adn.md
packages/charts/src/lib/observablePlot/DemoTooltip.svelte
packages/charts/src/lib/observablePlot/ObservablePlot.stories.svelte
packages/charts/src/lib/observablePlot/ObservablePlot.svelte
packages/charts/src/lib/observablePlot/exampleData.js

This allow custom tooltip components to be used with observable plot wrapper.
**Why?**
To allow more control over tooltip appearance.
No.

allow custom tooltip to be used with observable plot wrapper

---

packages/maps/src/lib/map/Map.svelte
packages/maps/src/lib/mapControlGroup/MapControlGroup.svelte

Adds initial documentation to `<Map>` and `<MapControlGroup>`.

Add docs to map & MapControlGroup

---

.changeset/fix-analytics-cookie.md
packages/ui/src/lib/analytics/AnalyticsAndCookieConsent.svelte

**What does this change and why?**
1. Fixes an issue where an application embedded in a non-london.gov.uk website wouldn't load cookie consent properly.
2. Moved general doc comment to Svelte script as comments in head scripts are not stripped by Svelte compiler.
3. Optimised code to be more concise and readable.
Within live Voter ID app.
Storybook and code comments.

Fix embedded not london.gov.uk site issues and remove docs

---

.changeset/jnofiw-jspdfm-ndkls.md
packages/ui/src/lib/sidebar/elements/sidebarTabs/SidebarTabLabel.svelte

This makes the text in SidebarTabLabel non-selectable.

make text in SidebarTabLabel non-selectable

---

.changeset/dfsas_fdsf_dfdsf.md
packages/ui/src/lib/header/NavLink.svelte

Currently a `NavLink` to the homepage (`/` route) of an app will never be highlighted when the app is deployed in production, as URLs have the structure `/<app-name>/route` rather than just `/route`, so `$page.url?pathname` will not match `/`.

Fix navlinks highlighting

---

packages/charts/src/lib/observablePlot/ObservablePlot.stories.svelte
packages/charts/src/lib/observablePlot/ObservablePlot.svelte
packages/charts/src/lib/observablePlotFragments/observablePlotFragments.ts

This provides a helper function to enable the registration of event handlers for marks in an Observable Plot plot.

enable registration of event handlers for svelte plots

---

.changeset/unfix-sidebar-header.md
packages/ui/src/lib/sidebar/Sidebar.svelte

Unfix the sidebar header so it scrolls with the section content
**Why?**
Because on small screens it leaves next to no real estate for the content. Users find it hard to see content.

Unfix sidebar header

---

.changeset/fix-embedded-analytics.md
packages/ui/src/lib/analytics/AnalyticsAndCookieConsent.svelte

Fixes an issue with `<AnalyticsAndCookieConsent>` component when embedded.
**Why?**
Tighter restrictions on the main website `www.london.gov.uk` caused a drop in permission when accessing the URL of `window.top`.
**How?**
This solution uses `document.referrer` to get the parent page URL instead.
The Digital Team are currently looking in to attributes and permissions issues regarding embedded apps (e.g. _Geolocation_ via _SameSite_ & _Secure_ policies). Their solution may prevent other future issues such as these.
In Cool Spaces and Wild & Free apps.

Fix same-site issues with embedded apps & CookieControl

---

.changeset/table-context-columns.svelte
packages/tables/src/lib/core/renderers/TextCellWithUncertainty.stories.svelte
packages/tables/src/lib/core/renderers/TextCellWithUncertainty.svelte
packages/tables/src/lib/introduction.mdx
packages/tables/src/lib/table/TableComplex.stories.svelte
packages/tables/src/lib/table/rows/DataRow.svelte

This enables the visual encoding applied to table cells to also depend on the values in other column(s).

Multi column encodings

---

.changeset/change-placeholder-image.md
packages/ui/src/lib/placeholderImage/PlaceholderImage.stories.svelte
packages/ui/src/lib/placeholderImage/PlaceholderImage.svelte

The `PlaceholderImage` component now contains a small fixed-size icon within a container. It no longer accepts props to control its styling
See https://github.com/Greater-London-Authority/ldn-viz-tools/issues/374

update PlaceholderImage component

---

.github/workflows/deploy-preview.yml
.github/workflows/deploy-storybook.yml
.github/workflows/lint.yml
.github/workflows/publish-packages.yml

This updates the version of actions used in our GitHub Action workflows, which addresses one of the warnings flagged in https://github.com/Greater-London-Authority/ldn-viz-tools/issues/378

update versions of actions in workflows

---

.changeset/button-alignment.md
packages/ui/src/lib/button/Button.stories.svelte
packages/ui/src/lib/button/Button.svelte

Fix alignment of tooltip trigger icon by applying flex class to outer `div` of `Button` component.
Before:
After:

Tweak button alignment

---

.changeset/default-input-hintext.md
packages/ui/src/lib/input/Input.stories.svelte
packages/ui/src/lib/input/Input.svelte

This setsa default hintLabel for Input components. 

Default hint label

---

.changeset/ffa-sfa-fadas.md
.changeset/ggs-fsgse-adasd.md
apps/docs/.storybook/main.ts
packages/ui/src/lib/index.ts
packages/ui/src/lib/themeSwitcher/Theme.svelte
packages/ui/src/lib/themeSwitcher/ThemeSwitcher.stories.svelte
packages/ui/src/lib/themeSwitcher/ThemeSwitcher.svelte
packages/ui/src/lib/themeSwitcher/themeStore.ts
packages/utils/src/main.ts
packages/utils/src/userPreference/Documentation.mdx
packages/utils/src/userPreference/mediaQueryStore.ts

Creates a mediaQueryStore factory function that listens to user preferences. Exposes two svelte stores that have boolean values for prefersDarkMode and prefersReducedMotion
**Why?**
Used for theme switching and animation accessibility settings
**How?**
see mediaQueryStore code
#250 
no
storybook
yes

Create media query stores motion and dark mode

---

packages/themes/tokens/design-tokens.tokens.json

Fixes the chart axis token to be correct value
adresses: #403

Axis token

---

.changeset/fix-select-multi-justvalue.md
packages/ui/src/lib/select/Select.stories.svelte
packages/ui/src/lib/select/Select.svelte

Until this fix, `justValue` would remain `undefined` for a `Select` component with `multiple` select enabled.

correctly set justValue when multiple is enabled for Select

---

.changeset/ten-ads-smell.md
packages/ui/src/lib/popover/Popover.svelte
packages/ui/src/lib/sidebar/elements/sidebarHint/SidebarHintModal.svelte
packages/ui/src/lib/tooltip/Tooltip.svelte

changes hint Icons to use mini theme
**Why?**
the smaller icons give better clarity
**How?**
specify mini theme
#430 
no
-
Storybook - with more coming in docs
n/a
- [na] If this adds a new component, is it exported via `index.js`?

Hint icons

---

.changeset/metal-crabs-look.md
packages/ui/src/lib/select/Select.svelte

Fixes missing chevron on select 
**Why?**
it was removed by mistake
**How?**
default showChevron prop to true
#475 

Restore chevron to select component

---

.changeset/rare-terms-marry.md
packages/ui/src/lib/checkBox/Checkbox.svelte
packages/ui/src/lib/checkBox/CheckboxGroup.stories.svelte
packages/ui/src/lib/checkBox/CheckboxGroup.svelte
packages/ui/src/lib/radioButton/RadioButtonGroup.svelte
packages/ui/src/lib/select/Select.svelte

Explicitly sets vertical spacing for checkbox and radio group components
**Why?**
This was happening due to leading on the labels - which collapsed when in a text-sm context
**How?**
Added space classes to containing divs
#470 
no
storybook
n/a
n/a

CheckboxGroup and InputGroup group spacing

---

packages/tables/src/lib/table/Table.stories.svelte

This removes an empty space below the column headers of the simple Table stories.

edit Table stories to remove empty space below column headers

---

.changeset/sfsd-sfsdf-sfsdf.md
packages/themes/.npmignore

Adds a `.npmignore` file - without this, npm exlcudes the files listed in `.gitignore`, so the generated CSS files aren't included in the published package and can't be accessed from other projects.

add .npmignore file for themes package

---

.changeset/dsdfsd-dsfsdf-fsdfsd.md
packages/charts/src/lib/index.js

This exports the exports defined in observablePlotFragments from the `charts` package.

export contents of observablePlotFragments

---

.changeset/popular-carrots-punch.md
packages/charts/src/lib/observablePlotFragments/observablePlotFragments.ts

updates the import path to themes package inside observable plot fragments
**Why?**
it was set to a relative path
**How?**
set it to correct package path
#508 
no
n/a
n/a
n/a
- [ x] Have you included changeset file?
- [ x] If this adds a new component, is it exported via `index.js`?

Package import path

---

.changeset/missing-util-package.md
.prettierrc
package.json
packages/charts/.prettierrc
packages/charts/package.json
packages/eslint-config-custom/package.json
packages/maps/.prettierrc
packages/maps/package.json
packages/tables/.prettierrc
packages/tables/package.json
packages/themes/package.json
packages/ui/package.json
packages/utils/package.json
packages/utils/src/colors/scales.ts

1. Adds `@ldn-viz/util` as a dependency for `@ldn-viz/ui`, `@ldn-viz/maps`, and `@ldn-viz/charts`
2. Adds `package.json` formatting via Prettier.
**Why?**
It broke.
Addresses: #503 
**It's not.** I don't know how to test it inside the repo. Unsure if the dependency can be placed in `devDependencies` or not.

Add utils packages to charts, maps, and ui packages

---

.changeset/unlucky-walls-enjoy.md
package-lock.json
packages/themes/package.json
packages/themes/themeStore.ts

defaults the user theme selection to system. And update the browser import to esm-env
**Why?**
before the default was light - using 'system' better honours user preference.
bowser import should be none svelte specific
**How?**
change config and change import to module
#512 
no
n/a
confluence
yes

Default theme set to system

---

.changeset/export-buttons-columnmapping.md
.changeset/table-columnmapping.md
packages/charts/src/lib/chartContainer/ExportBtns.svelte
packages/tables/src/lib/table/Table.stories.svelte
packages/tables/src/lib/table/Table.svelte
packages/tables/src/lib/table/TableContainer.svelte

- update to use the new Image/Data download buttons in ExportBtns component
- add a `columnMapping` prop to the `ExportBtns` component, to allow data columns to be renamed before download

update to use the new Image/Data download buttons in ExportBtns component

---

.changeset/geocoder-selected-name.md
packages/maps/src/lib/mapControlLocationSearch/MapControlGeocoder.svelte
packages/ui/src/lib/geolocation/Geocoder.stories.svelte
packages/ui/src/lib/geolocation/Geocoder.svelte
packages/ui/src/lib/geolocation/GeocoderSuggestionList.svelte

Updates `<Geocoder>` so that the input's text is the address or name of the selected location when a location is selected.
**Why?**
So users know what they selected.
Addresses: #333 
Storybook.
Storybook.

Set selected location in Geocoder as query text 

---

.changeset/quiet-apricots-happen.md
package-lock.json
packages/ui/src/lib/header/Header.stories.svelte
packages/ui/src/lib/header/Header.svelte
packages/ui/src/lib/header/NavLinks.svelte
packages/ui/src/lib/modal/Modal.stories.svelte
packages/ui/src/lib/modal/Modal.svelte

adds props to the Global Header and to the Modal Header components that allows them to be either light or dark themed individually - defaults to dark
**Why?**
Default - even in light mode, is for these elements to be themed dark
**How?**
accepts props with defaults. This allows for overriding to light theme colors if ever required. This is the same behaviour as the sidebar.
#562 
no
storybook
storybook
yes

Header and Modal theme colors

---

.changeset/polite-rings-help.md
packages/maps/src/lib/mapCursorEvent/MapCursorEvent.stories.svelte

I corrected the `GeoJSON Feature` types of `handlerArgType` in `MapCursorEvent.stories.svelte`. They are now `GeoJSON.Feature` which matches the exported interface from the `@types/geojson` package (`GeoJSONFeature` causes type errors because it doesn't exist).

Map cursor event type fix

---

.changeset/geocoder-placeholder.md
packages/maps/src/lib/mapControlLocationSearch/MapControlGeocoder.svelte
packages/maps/src/lib/mapControlLocationSearch/MapControlLocationSearch.stories.svelte
packages/maps/src/lib/mapControlLocationSearch/MapControlLocationSearch.svelte
packages/ui/src/lib/geolocation/Geocoder.stories.svelte
packages/ui/src/lib/geolocation/Geocoder.svelte

Ths allows custom placeholder text in `Geocoder`, `MapControlGeocoder` and `MapControlLocationSearch` components. 
**Why?**
This will be useful in the new Small Sites map, where selecting a location sorts the list of sites by proximity to it.

Allow custom placeholder text in geocoder

---

.changeset/tables-axis-renders.md
packages/tables/src/lib/core/lib/dataObj.ts
packages/tables/src/lib/core/renderers.ts
packages/tables/src/lib/table/TableHSDS.stories.svelte

This allows axis renderers to be specified by name (as strings, rather than Svelte components) in table specifications.

allow axis renderers to be specified as strings

---

.changeset/diverging-bar-props.md
packages/tables/src/lib/core/renderers/BarDivergingCell.stories.svelte
packages/tables/src/lib/core/renderers/BarDivergingCell.svelte

`BarDivergingCell` renderer now accepts `textSize`/`positiveColor`/`negativeColor` props

add more props to BarDivergingCell

---

.changeset/table-height.md
packages/tables/src/lib/table/Table.svelte
packages/tables/src/lib/table/TableComplex.stories.svelte

This updates the `Table` to no longer set a fixed height unless the `virtualise` prop is `true`.

don't fix table height unnecessarily

---

.changeset/table-optional-top-rule.md
packages/tables/src/lib/table/Table.svelte
packages/tables/src/lib/table/TableHSDS.stories.svelte

This allows the horizontal rule above the header of a table to be disabled, to match the design in the Figma mockups for the HSDS hub.

Tables: allow rule above table header to be disabled

---

.changeset/link-button.md
packages/ui/src/lib/button/Button.stories.svelte
packages/ui/src/lib/button/Button.svelte

This has uses including linking to pages on the datastore from the new small sites map.
Here's a preview link that lets you inspect the DOM that is created (but the links don't actually work, due to how the embedding of stories inside storybook is done): https://dev.ldn-gis.co.uk/storybook-link-button-new-tab/?path=/story/ui-button--with-link-opening-in-new-tab

Add prop to Button component to specify that link should be opened in new tab

---

.changeset/slow-boxes-doubt.md
package-lock.json
packages/charts/src/lib/index.js
packages/charts/src/lib/observablePlot/ObservablePlot.stories.svelte
packages/charts/src/lib/observablePlot/ObservablePlot.svelte
packages/charts/src/lib/observablePlot/ObservablePlotInner.stories.svelte
packages/charts/src/lib/observablePlot/ObservablePlotInner.svelte
packages/eslint-config-custom/index.js

`ObservablePlot` wraps around `ChartContainer` and `ObservablePlotInner` components. `ObservablePlotInner` now contains the plot logic that used to live in `ObservablePlot`.
You can now also add a `controls` slot to keep `Select` or other inputs with the relevant charts.
**Why?**
Adding desired functionality and clarity to the structure of the `ObservablePlot` component.

Refactor ObservablePlot to extract ObservablePlotInner and add controls slot

---

.changeset/partially-sortable-table.md
packages/tables/src/lib/table/Table.stories.svelte
packages/tables/src/lib/table/rows/headerRows/ColumnHeadingRow.svelte

This allows users to specify that some columns in a table should not be sortable.

allow only some columns in table to be made sortable

---

.changeset/little-paws-greet.md
packages/ui/src/lib/radioButton/RadioButtonGroup.svelte

`hintLabel` is now an optional prop in `RadioButtonGroup`, to match intended functionality.

fixed hintLabel so it's optional

---

packages/ui/src/lib/datepicker.mdx

Add a page linking to the datepicker component we use.
Preview: https://dev.ldn-gis.co.uk/storybook-document-datepicker/?path=/docs/ui-datepicker-datepicker--documentation

add page about datepickers

---

.changeset/silly-cherries-wave.md
packages/charts/src/lib/chartContainer/ChartContainer.svelte
packages/charts/src/lib/chartContainer/ExportBtns.svelte
packages/tables/src/lib/table/TableContainer.svelte

adds default padding to images downloaded via "download as Png" button
**Why?**
padding wasn't being added
**How?**
n
storybook

Png download padding

---

.changeset/sidebar-start-open.md
packages/ui/src/lib/appShell/AppShell.stories.svelte
packages/ui/src/lib/appShell/AppShell.svelte

Fix bug that caused `AppShell` to always acts as if the `startOpen` prop was `false`.
Fixes #673

respect startOpen prop in AppShell

---

.changeset/radio-checkbox-spacing.md
packages/themes/ldn-theme.js

Switches css width and height of form-checkbox and form-radio class from rem to em
**Why?**
Using rem meant that inside a text-sm context the elements, when grouped were too close.
**How?**
Change to ldn-viz theme global css
no
no
storybook
na
na
y

use em instead of rem for width and height of radios/ checkboxes

---

.changeset/layer-control-z-index.md
packages/ui/src/lib/layerControl/ColorPicker.svelte
packages/ui/src/lib/layerControl/OpacityControl.svelte
packages/ui/src/lib/layerControl/ResizeControl.svelte

Increase z-index of popover controls in LayerControl component so that they do not open behind sidebars

---

.changeset/geocoder-icons.md
packages/ui/src/lib/geolocation/Geocoder.svelte

This fixes #703 
Preview: https://dev.ldn-gis.co.uk/storybook-double-clear-icon/?path=/docs/maps-mapcontrols-mapcontrollocationsearch--documentation

prevent Chrome drawing a second clear icon in Geocoder when used in a Map

---

.changeset/multiple-radiobuttongroupsolid.md
packages/ui/src/lib/radioButtonSolid/RadioButtonSolid.stories.svelte
packages/ui/src/lib/radioButtonSolid/RadioButtonSolid.svelte

See "Using multiple instances" story on https://dev.ldn-gis.co.uk/storybook-radiobuttongroupsolid-name/?path=/docs/ui-radiobuttongroupsolid--documentation

include name in the id of RadioButtonSolid (fix #665)

---

.changeset/table-download-buttons.svelte
packages/tables/src/lib/table/Table.svelte
packages/tables/src/lib/table/TableContainer.svelte

Default to hide SVG option in image download button, as this will not give the exported result of downloading an image of the entire table

hide SVG option by default in table image export button

---

packages/maps/src/lib/mapControlGroup/MapControlGroup.stories.svelte

This moves the text in some `MapControlGroup` stories out of `div`s inside the story, and into the paragraph before the story.

move text out of divs inside MapControlGroup stories (fix #767)

---

.changeset/popover-z-index.md
packages/ui/src/lib/popover/Popover.svelte

This increases the z-index of the popover component, to enure it is drawn above the Sidebar component.
This fixes a regression in the `LayerControl` component that appeared when it was refactored to use the `Popover` component/

Increase popover z-index

---

.changeset/moody-zebras-doubt.md
packages/ui/src/lib/layerControl/LayerContolGroup.stories.svelte
packages/ui/src/lib/layerControl/LayerControlGroup.svelte

Makes border of layer control group parent appear as standard grey
**Why?**
Because it is logical that it should.
**How?**
By removing hard coded color hex
Also updated the 'Hide controls size and opacity controls for some layers' story to remove the disabled option. So demonstrating the change.
no
Storybook
Storybook
N/A
Yes

Remove hard coded color from layer control group parent

---

.changeset/table-sort-icons.md
packages/tables/src/lib/core/renderers/Header.svelte
packages/tables/src/lib/table/rows/headerRows/ColumnHeadingRow.svelte

This fixes https://github.com/Greater-London-Authority/ldn-viz-tools/issues/469

change table sort icons to indicate applied sort direction

---

.changeset/chilled-rabbits-shake.md
.changeset/weak-years-grow.md
package-lock.json
packages/charts/package.json
packages/charts/src/lib/chartContainer/ChartContainer.svelte
packages/charts/src/lib/chartContainer/Footer.svelte
packages/charts/src/lib/examples/LineChart.stories.svelte
packages/charts/src/lib/observablePlot/ObservablePlot.svelte
packages/charts/src/lib/observablePlot/ObservablePlotInner.svelte
packages/charts/src/lib/observablePlotFragments/observablePlotFragments.ts
packages/ui/src/lib/index.ts

**Originally**
I've added `ariaLabel` and `ariaHidden` attributes to the example line chart, to demonstrate how we can incorporate accessibility best practice.
I don't think this is quite perfect due to the following:
- Adding ariaHidden: 'true' to Plot marks, successfully hides the SVG elements from the screen reader. Except for the axis marks, if they have a label.
- `ariaDescription` doesn’t appear to work inside marks or the spec - the screen reader ignores it
- `ariaLabel` on the `Plot.line()` makes the line disappear
- `ariaLabel` on the spec (outside of marks) DOES work but the screen reader still reads the y axis label, as it's not hidden
- The `ariaLabel` isn't achieving much more than the subTitle is, so we could instead replace it with a slightly more …

Added ariaHidden to exampleLineCharts

---

.changeset/text-color-picker.md
packages/utils/package.json
packages/utils/src/colors/colorWithBestContrast.test.js
packages/utils/src/colors/colorWithBestContrast.ts
packages/utils/src/main.ts

This add a colorWithBestContrast function that selects which of two potential text colors has better contrast with given background color.
Yes - `apca-w3` and (transitively) `colorparsely`.
There are some vittest tests.

add colorWithBestContrast function

---

.changeset/famous-gorillas-tie.md
packages/ui/src/lib/button/Button.svelte
packages/ui/src/lib/index.ts
packages/ui/src/lib/modal/Modal.stories.svelte
packages/ui/src/lib/modal/Modal.svelte
packages/ui/src/lib/multipleActionButton/MultipleActionButton.svelte
packages/ui/src/lib/overlay/Overlay.stories.svelte
packages/ui/src/lib/overlay/Overlay.svelte
packages/ui/src/lib/overlay/Trigger.svelte
packages/ui/src/lib/popover/Popover.stories.svelte
packages/ui/src/lib/popover/Popover.svelte
packages/ui/src/lib/tooltip/Tooltip.stories.svelte
packages/ui/src/lib/tooltip/Tooltip.svelte

- Added `Overlay` component to enable choice of tooltip, modal or popover in components like `InputWrapper`
- Added `Trigger` component which handles opening different overlays and demonstrated implementation. It's in a slot, so it is optional (can be overridden with custom button trigger)
- Demonstrated implementation of Overlay, Tooltip, Modal and Popover in Overlay stories and relevant individual component stories in Storybook
- Refactored Button `customAction` prop to be generic
**Why?**
Review and refactor of our similar components to:
- Align implementation
- Align the technologies
- Align the component API
Modal, tooltips and popovers had slightly different implementations and we wanted to make our components flexible enough for the trigger to trigger the …

UI overlays: Tooltips, Popovers, Modals

---

.changeset/rotten-turtles-brush.md
package-lock.json
packages/charts/src/lib/chartContainer/ChartContainer.svelte
packages/charts/src/lib/chartContainer/Footer.svelte

- The `alt` is now read before the title, subtitle etc in a chart (using `ChartContainer`) so the context is clearer for screen reader users
- I've added `data-capture-ignore` to the 'View description' button in ChartContainer > Footer, so it's not included in image download
**Related issues**: resolves #812
No
Storybook
Storybook
N/A
Yes

Ally: fixed order of chart alt and ignore View description in image download

---

.changeset/map-control-positions.md
packages/maps/src/lib/mapControlGroup/MapControlGroup.svelte

Before: https://greater-london-authority.github.io/ldn-viz-tools/?path=/story/maps-mapcontrols-mapcontrolgroup--positioning-labels
After: https://dev.ldn-gis.co.uk/storybook-map-control-group-positioning/?path=/story/maps-mapcontrols-mapcontrolgroup--positioning-labels

shift map control groups to avoid overlap with attribution (fix #669)

---

.changeset/geocoder-clear-callback.md
packages/maps/src/lib/mapControlLocationSearch/MapControlGeocoder.svelte
packages/maps/src/lib/mapControlLocationSearch/MapControlLocationSearch.stories.svelte
packages/maps/src/lib/mapControlLocationSearch/MapControlLocationSearch.svelte
packages/ui/src/lib/geolocation/Geocoder.svelte

`Geocoder`, `MapControlGeocoder`, and `MapControlLocationSearch` accept a callback function to call when the user clears the search box.
This is useful in apps like the new Small Sites map, where clearing the search box/de-selected the selected location should reset the list of sites.

add callback function to be called when geocoder searchbox cleared

---

.changeset/page-metadata-types.md
packages/ui/src/lib/pageMetadata/PageMetadata.svelte

This sets types for some props of `PageMetadata`. Currently, these implicitly have type `undefined`, and so providing a value results in a type error `Type string is not assignable to type undefined`.

set types of PageMetadata props

---

.changeset/wet-roses-brake.md
packages/charts/src/lib/chartContainer/Footer.svelte
packages/ui/src/lib/button/Button.stories.svelte
packages/ui/src/lib/button/Button.svelte
packages/ui/src/lib/overlay/Trigger.svelte

Adds a xs size variation for buttons (24px) and also adds a 'slim' boolean that allows for buttons to align with text or other ui elements in certain contexts
**Why?**
Required in various scenarios
**How?**
additional prop and css tweaks
#817 
no
storybook
stories
n/a

Button alignment

---

packages/ui/src/lib/button/AsyncButton.stories.svelte

Updates story, where incorrect use of square button cause a11y warning. This is not a fault in the component, but a misapplication/ bad example that has been updated.
**Why?**
Don't want failing all examples
**How?**
Buttons should have text so added to square button example
#736
no
storybook
storybook
na

adress a11y issues in async button story

---

.changeset/full-width-button.md
packages/ui/src/lib/button/Button.stories.svelte
packages/ui/src/lib/button/Button.svelte
packages/ui/src/lib/dataDownloadButton/DataDownloadButton.stories.svelte
packages/ui/src/lib/dataDownloadButton/DataDownloadButton.svelte
packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.stories.svelte
packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.svelte
packages/ui/src/lib/multipleActionButton/MultipleActionButton.svelte

This adds a prop that allows buttons and MultipleActionButtons to fill the width of their parent.
**Related issues**: 
https://github.com/Greater-London-Authority/ldn-viz-tools/issues/791
**Preview**: https://dev.ldn-gis.co.uk/storybook-full-width-buttons/?path=/docs/ui-components-buttons-datadownloadbutton--documentation

enable full-width buttons and MultipleActionButtons

---

apps/docs/.storybook/preview.ts
apps/docs/.storybook/withThemeByClassNameStore.ts
packages/ui/src/lib/layerControl/LayerControl.stories.svelte

Upadtes the theme switching in storybook to both honor system settings and update the universal theme store (more closely aligning 'our theme' used in components to the storybook theme switcher)
**Why?**
Theme switching in sb was a) buggy if set to system and b) did not update the theme store used for our component theme variables
**How?**
Updated storybook decorator
#853 
no
sb 
n/a
yes

update theme using storybook controls

---

.changeset/two-poets-hope.md
packages/ui/src/lib/checkBox/Checkbox.svelte
packages/ui/src/lib/checkBox/CheckboxGroup.stories.svelte
packages/ui/src/lib/checkBox/CheckboxGroup.svelte
packages/ui/src/lib/layerControl/ColorPicker.svelte
packages/ui/src/lib/layerControl/LayerContolGroup.stories.svelte
packages/ui/src/lib/layerControl/LayerControl.stories.svelte
packages/ui/src/lib/layerControl/LayerControl.svelte
packages/ui/src/lib/layerControl/LayerControlGroup.svelte
packages/ui/src/lib/layerControl/OpacityControl.svelte
packages/ui/src/lib/layerControl/ResizeControl.svelte
packages/ui/src/lib/radioButton/RadioButton.svelte
packages/ui/src/lib/radioButton/RadioButtonGroup.stories.svelte
packages/ui/src/lib/radioButton/RadioButtonGroup.svelte
packages/ui/src/lib/radioButtonSolid/RadioButtonGroupSolid.svelte
packages/ui/src/lib/radioButtonSolid/RadioButtonSolid.stories.svelte
packages/ui/src/lib/radioButtonSolid/RadioButtonSolid.svelte

a) Adds input wrapper to grouped inputs
b) Uses 'overlay' instead of tooltip for checkbox/ radio hints
c) Updates layer control to allow indivvidual control triggers to be disabled
**Why?**
Universality
**How?**
Use exiting components 
**Related issues**: 
#667, #834, #818
no
Storybook
Storybook
yes
yes

Input hints

---

packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.svelte

When the `ChartContainer` componenet uses `alignMultiple={true}`, then the chart container `div` uses `display: contents`. This means it has no defined size, so the `ImageDownloadButton` would download an image whose size was `2 * padding` x `2 * padding`. 
This PR tries to handle this case by looking at the size of the child elements. This seems to result in reasonably sized PNG images, but the padding does not seem to be being appleid correctly: it all appears at the bottom and right, rather than being evenly assigned to the top/bottom and left/right.

calculate image size when ChartContainer uses alignMultiple

---

.changeset/big-ladybugs-decide.md
packages/ui/src/lib/popover/Popover.stories.svelte
packages/ui/src/lib/popover/Popover.svelte

- Popover now has openFocus set to content, to enable screen reader accessibility
- Also created optional `defaultOpenFocus` prop.
- This is useful for cases where the first element in the popover is interactive, as the default behaviour of focusing the first interactive element is appropriate.
- Otherwise, it is set to false, for the majority of cases where the first interactive element is the close button, which would skip over the entire contents of the popover
Fixes #751
Relates #834
No
Storybook
Storybook
N/A
Yes

Ally: Popover screen reader accessibility

---

.changeset/chatty-carrots-search.md
packages/ui/src/lib/toaster/Toast.svelte

- Applied correct role to Toast component so screen reader can identify it and read out the contents when it pops up.
**Why?**
Accessibility
**How?**
Changed `role="dialog"` to `role="alert"`
Closes #760
Relates #367
No
Storybook
Storybook
N/A
Yes

Ally: fixed accessibility issues in Toast component

---

.changeset/proud-toes-happen.md
packages/ui/src/lib/select/Select.svelte

- `Select` component now uses `id` prop correctly to connect label and input elements
**Why?**
- For accessibility, labels and inputs should be linked. This means when you click the label, it focuses the input.
**How?**
- Now pass `id` into `SvelteSelect` (previously it was only passed into `InputWrapper`) 
#367 
Closes #746 
No
Storybook
Storybook
N/A
Yes

Ally: added `id` prop to `SvelteSelect`

---

packages/charts/src/lib/introduction.mdx

This improves the documentation, and should help to avoid problems like https://github.com/Greater-London-Authority/ldn-viz-tools/pull/833
Preview: https://dev.ldn-gis.co.uk/storybook-charts-docs/?path=/docs/charts-introduction--documentation

edit introduction.mdx for charts package

---

.changeset/slimy-snakes-drum.md
packages/ui/src/lib/checkBox/Checkbox.svelte
packages/ui/src/lib/checkBox/CheckboxGroup.stories.svelte
packages/ui/src/lib/checkBox/CheckboxGroup.svelte
packages/ui/src/lib/layerControl/LayerContolGroup.stories.svelte
packages/ui/src/lib/layerControl/LayerControlGroup.svelte

I've updated the `LayerControlGroup` and `CheckboxGroup` components to use semantic html for better screen reader accessibility. I've also updated `Checkbox` to improve screen reader accessibility for tooltips inside checkbox components.
**Why?**
Improving screen reader accessibility
**How?**
`LayerControlGroup` and `CheckboxGroup` now have:
- `id` and `role="group"` attributes on the div that wraps around the `LayerControl` or `Checkbox` inputs
- `ariaLabel` prop to describe the purpose of the LayerControlGroup/CheckboxGroup to screen reader users
- `<ul>` element surrounding the options, with each option nested in an `<li>` element so screen reader users know the options are connected and how many there are
`Checkbox` now explicitly nests a `Trigger` component …

A11y: improve sr accessibility in CheckboxGroup and LayerControlGroup

---

.changeset/table-aria.md
packages/tables/src/lib/core/renderers/Header.svelte
packages/tables/src/lib/table/Table.svelte
packages/tables/src/lib/table/TableHeader.svelte
packages/tables/src/lib/table/rows/DataRow.svelte
packages/tables/src/lib/table/rows/Scaffolding.svelte
packages/tables/src/lib/table/rows/headerRows/AxisRow.svelte
packages/tables/src/lib/table/rows/headerRows/ColumnHeadingRow.svelte

This improves the ARIA for the table component.
For the [basic example table](https://dev.ldn-gis.co.uk/storybook-table-aria/?path=/story/tables-components-table--default), Vocie Assitant allows navigation with Control-Option-[up/down/left/right] and correctly describes cell contents, e.g.:
* "First Name Margharet. Column 1 of 3" - when shifting between columns
* "Row 14 of 21: Margharet" - when shifting between rows

tables: improve ARIA

---

.changeset/brown-glasses-shop.md
packages/ui/src/lib/checkBox/CheckboxGroup.svelte
packages/ui/src/lib/layerControl/LayerContolGroup.stories.svelte
packages/ui/src/lib/layerControl/LayerControl.stories.svelte
packages/ui/src/lib/layerControl/LayerControl.svelte
packages/ui/src/lib/layerControl/LayerControlGroup.svelte

- `LayerControlGroup` now passes `name` into `LayerControl`
- `LayerControl` now passes `name` into `Checkbox`, in addition to `Radio`
- `LayerControlGroup` and `CheckboxGroup` now have an `aria-controls` attribute on the checkbox that toggles all controls, with a value equal to the ids for all controls
**Why?**
For better accessibility
No
Storybook
Storybook
N/A

A11y: updated LayerControl and LayerControlGroup to apply name to checkboxes

---

.changeset/wicked-singers-own.md
packages/ui/src/lib/sidebar/Sidebar.stories.svelte
packages/ui/src/lib/sidebar/Sidebar.svelte

The main content of `Sidebar` is now wrapped in an `<aside>` rather than a `<div>` for better screen reader navigation between main content and sidebar.
`Sidebar` now takes two `ariaLabel` props:
- `sidebarAriaLabel` to tell screen reader users what the sidebar is for
- `tabsAriaLabel` to tell screen reader users what the tabsList is for (renamed from `ariaLabel` to accommodate the need for a sidebar ariaLabel.
This is to address the last bits of accessibility updates needed for the sidebar as outlined in #755.
**Related issues**: Resolves #755 
No
Storybook
Storybook
N/A

A11y: updated Sidebar to use an aside and ariaLabel props

---

.changeset/itchy-rings-burn.md
packages/ui/src/lib/layerControl/ColorPicker.svelte
packages/ui/src/lib/layerControl/LayerContolGroup.stories.svelte
packages/ui/src/lib/layerControl/LayerControl.stories.svelte
packages/ui/src/lib/layerControl/LayerControl.svelte
packages/ui/src/lib/layerControl/LayerControlGroup.svelte
packages/ui/src/lib/layerControl/layerControlUtils.ts

`LayerControlGroup`, `LayerControl` and `ColorPicker` accept a custom list of colour tokens, called `colorNames`.
**Why?**
This allows for use in maps where specific colours are required (e.g. requiring a light blue for water).
**How?**
`colorNames` is initialised as an empty array. If an array of token strings is passed in, it will show those colours. Otherwise, if it's empty, it will default to standard categorical colours, as normal.
**Related issues**: Closes #959 
No
Storybook
Storybook
Yes (colorNames are token names, so change depending on the theme)

ColorPicker accepts custom colours

---

.changeset/fix-token-refresh.md
packages/ui/src/lib/auth/HandleRedirectFromAuth.svelte

Refreshing access tokens was broken due to a mistake when re-factoring to extract the auth components from the initial demo app into re-suable components that accept a config object.

fix token refresh

---

.changeset/two-meals-perform.md
apps/docs/.storybook/withThemeByClassNameStore.ts
package-lock.json
packages/ui/src/lib/layerControl/ColorPicker.svelte
packages/ui/src/lib/layerControl/LayerControl.stories.svelte
packages/ui/src/lib/layerControl/LayerControl.svelte
packages/ui/src/lib/overlay/Trigger.svelte
packages/ui/src/lib/tooltip/Tooltip.svelte

`ColorPicker` now has the following:
- Each colour option has a tooltip with the name of the colour, for better accessibility
- When you hover over a colour, a ring appears
- Active colour (currently selected) has a ring around it 
**Why?**
Improve accessibility
**Related issues**: Resolves #961 
No
Storybook
Storybook
Yes
Requires design review of focus state as this is currently not visible.

A11y: Added ColorPicker tooltip, hover and active states

---

.changeset/sixty-bulldogs-scream.md
packages/ui/src/lib/sidebar/Sidebar.svelte
packages/ui/src/lib/sidebar/elements/sidebarTabs/SidebarTabList.svelte

Fixed style regression from #973 where sidebar tabs were not appearing correctly in horizontal orientation.
Before:
After:
**Why?**
Fix styling issue.
**How?**
`SidebarTabList` accepts a `placement` prop from `Sidebar` instead of getting `$sidebarPlacementFromContext` which sometimes doesn't exist.
No
Storybook
Storybook
N/A

Fixed: sidebar tabs now appear correctly when oriented horizontally

---

.changeset/gold-deers-end.md
packages/charts/src/lib/examples/LineChart.stories.svelte
packages/charts/src/lib/observablePlotFragments/observablePlotFragments.ts

defaultArea plot fragment now sets a default `fillOpacity` instead of `opacity`. This makes it consistent with the other plot fragments.
Potentially may affect existing area charts using `opacity`
Storybook
[Storybook](https://dev.ldn-gis.co.uk/storybook-update-plot-fragments/?path=/docs/charts-example-charts-linechart--documentation)
N/A

changed defaultArea to use fillOpacity instead of opacity

---

.changeset/deckgl-tooltips-popovers.md
packages/maps/src/lib/index.js
packages/maps/src/lib/mapDeckOverlay/MapDeckOverlay.stories.svelte
packages/maps/src/lib/mapDeckPopovers/DefaultPopover.svelte
packages/maps/src/lib/mapDeckPopovers/MapDeckPopovers.stories.svelte
packages/maps/src/lib/mapDeckPopovers/MapDeckPopovers.svelte
packages/maps/src/lib/mapDeckPopovers/demo/DemoPopoverComponent.svelte
packages/maps/src/lib/mapDeckPopovers/stores.ts
packages/maps/src/lib/mapDeckTooltips/MapDeckTooltips.stories.svelte
packages/maps/src/lib/mapDeckTooltips/MapDeckTooltips.svelte
packages/maps/src/lib/mapDeckTooltips/demo/DemoTooltipComponent.svelte
packages/maps/src/lib/mapDeckTooltips/stores.ts
packages/maps/src/lib/mapPopover/MapPopover.svelte

This adds `MapDeckPopovers` and `MapDeckTooltips` components to easily add popovers or tooltips to multiple Deck.gl layers.

add MapDeckPopovers and MapDeckTooltips components

---

.changeset/maps-exports.md
packages/maps/src/lib/index.js

This adds some exports needed to use the `MapDeckPopovers` and `MapDeckTooltips` components

add some exports form maps package

---

.changeset/angry-pens-sort.md
packages/charts/src/lib/observablePlotFragments/observablePlotFragments.ts
packages/charts/src/lib/observablePlotFragments/plot.ts

Added:
- defaultRect and defaultBar plot fragments (as per Mike's request in #882)
Changed:
- plot function now checks for `options.facet` as well as `options.fy/fx` to apply default facet styling
**Related issues**: Resolves #882 

Sv5 - Added default plot fragments

---

.changeset/famous-boxes-hope.md
packages/maps/src/lib/mapControlLocationSearch/MapControlGeocoder.svelte
packages/maps/src/lib/mapControlLocationSearch/MapGeocoderAdapterMapBox.ts
packages/maps/src/lib/mapControlLocationSearch/map-layer.ts
packages/ui/src/lib/geolocation/Geocoder.svelte
packages/ui/src/lib/geolocation/GeocoderAdapter.ts

Updating geocoder to use Searchbox API. Already done in svelte4 but moving over to svelte5.
**Why?**
To include POI in geocoder search
**How?**
Porting over changes from svelte4 geocoder
NA
No
Test in storybook
Change set
NA
Yes

Added changes from svelte4 geocoder (issue #912) into svelte5 branch

---

packages/maps/src/lib/index.ts

Exporting store and functions from MapDeckTooltips store file:
- mousedOverObject store
- onMouseOverTooltipHandler
for use in projects

export store and onHover function from mapDeckTooltips

---

.changeset/observable-color-defaults.md
packages/charts/src/lib/observablePlotFragments/observablePlotFragments.ts

Observale Plot should determine the scale type automatically. Setting it to `ordinal` by default will mean that it will need to be explicitly set if a different scale type is required (otherwise, instead of being rendered as a nice interpretabl color-ramp, teh legend for a continuous color scale will be drawn as a large number of color chips, one per unique value in the data).

don't set color scales to ordinal type as default

---

.changeset/icy-lies-relax.md
packages/maps/src/lib/map/MapLibre.svelte

Replaces side effect with onresize event listener, to resize MapLibre instance without flickering.
**Why?**
Fix flickering
**How?**
**Related issues**: #1129 
No
[Storybook](https://dev.ldn-gis.co.uk/storybook-sv5-stopMapFlicker/?path=/story/maps-components-mapcontextlayers-boroughscontextlayer--default)
compared to [svelte5 branch](https://dev.ldn-gis.co.uk/storybook-svelte5/?path=/story/maps-components-mapcontextlayers-boroughscontextlayer--default)
[Storybook](https://dev.ldn-gis.co.uk/storybook-sv5-stopMapFlicker/?path=/story/maps-components-mapcontextlayers-boroughscontextlayer--default)
N/A

SV5: MapLibre - fix map flickering on resize

---

.changeset/proud-suits-appear.md
.changeset/sv5-mapDeckTooltips.md
packages/maps/src/lib/mapDeckTooltips/MapDeckTooltips.svelte

Replaces custom z-index on `MapDeckTooltips` with `.maplibregl-popup` class (which applies z-index: 10, aligning it with MapControlGroup components).
**Why?**
Fix tooltips appearing over Modals
**How?**
No
Storybook
Storybook

sv5: MapDeckTooltips z-index
