Greater-London-Authority/ldn-viz-tools

packages/ui/src/lib/modal/Modal.stories.svelte
This shows how close/confirm buttons can be implemented, but they are not styled as they should be yet.
=> Add a story showing how to modal close buttons

.github/workflows/lint.yml
This will initially log errors, due to some issues logged in https://github.com/Greater-London-Authority/ldn-viz-tools/pull/65 (not yet merged), and CRLD/LF line-ending encoding issues.
=> Create Action to lint pull requests

packages/ui/src/lib/Introduction.mdx, packages/ui/src/lib/button/Introduction.mdx, packages/ui/src/lib/modal/Introduction.mdx, packages/ui/src/lib/select/Introduction.mdx
This adds a "Docs" section for the components that appears before the stories.
=> Component intros

apps/docs/.storybook/preview-head.html, packages/themes/ldn-theme.js
This udpates the Storybook config so that components in stories use the correct font (Roboto).
=> Storybook fonts

.changeset/tasty-socks-argue.md, package-lock.json, packages/ui/src/lib/button/Button.stories.svelte, packages/ui/src/lib/button/Button.svelte
Changes the appearance of `Button` component, and the props it accepts.
=> Buttons update

.changeset/old-goats-build.md, packages/ui/src/lib/checkBox/Checkbox.svelte, packages/ui/src/lib/checkBox/CheckboxGroup.svelte
In `CheckboxGroup` component , replace select/clear all buttons with a checkbox.
This brings the implementation closer to the design in Figma.
=> in CheckboxGroup replace select/clear all buttons with checkbox

package-lock.json, packages/ui/src/lib/button/Button.stories.svelte, packages/ui/src/lib/button/Button.svelte
This adds a story showing off the new button designs, similar to the table in Figma - related to #132.
=> Table of buttons

README.md
This priovides slightly more documentation about the release process.
=> Document release process better

.changeset/modern-yaks-whisper.md, packages/ui/src/lib/spinners/Spinner.stories.svelte, packages/ui/src/lib/spinners/Spinner.svelte
Removed hard coded hex values and replaced with tailwind classes
**Why?**
To work correctly in dark / light mode
**How?**
Tailwind classes applied
https://github.com/Greater-London-Authority/ldn-viz-tools/issues/151
No
Storybook
Storybook
Yes!!! ;)
Yes
- [X ] Have you included changeset file?
=> dark mode defaults

.changeset/jnuu-qyegy-nsc.md, packages/ui/src/lib/index.js
The exports the `Input` and `InputWrapper` components. Fixes #204 .
=> Export inputs

.changeset/fix-map-resize, packages/maps/src/lib/map/Map.svelte
Fixes map not resizing when container resizes programtically.
**Why?**
It broken.
=> Map resize fix

.changeset/fsdfe-fdgr-sww.md, packages/ui/src/lib/colorLegends/ColorLegend.stories.svelte, packages/ui/src/lib/colorLegends/ColorLegend.svelte
`ColorLegend` component now correctly updates when domain of threshold scale is updated
=> Fix scale updates

.changeset/dhdhd-ororo-htbgn, apps/docs/.storybook/ciuStorybookTheme.ts, apps/docs/.storybook/preview.ts, packages/ui/src/lib/toaster/Toast.svelte, packages/ui/src/lib/toaster/Toaster.stories.svelte, packages/ui/src/lib/toaster/documentation.mdx, packages/ui/src/lib/toaster/toaster.ts
Swaps border for `shadow-lg` in toast messages.
**Why?**
Better looking.
=> Add shadow to toasts

.changeset/jfiiof-qhwq-eer.md, packages/ui/src/lib/index.js
Export the tooltip component so that it can be used in projects.
=> export Tooltip component

.changeset/qwwe-asd-cse.md, packages/ui/src/lib/header/Header.svelte
This updates the styling of the `Header` to match Figma. @ChrisKnightLDN, please can you check this is correct?
=> Update styling of Header.svelte

.changeset/nervous-rivers-repair.md, packages/ui/src/lib/appShell/AppShell.stories.svelte, packages/ui/src/lib/appShell/AppShell.svelte, packages/ui/src/lib/modal/Modal.stories.svelte, packages/ui/src/lib/modal/Modal.svelte, packages/ui/src/lib/sidebar/Sidebar.stories.svelte, packages/ui/src/lib/sidebar/Sidebar.svelte, packages/ui/src/lib/sidebar/elements/sidebarHeader/SidebarHeader.stories.svelte, packages/ui/src/lib/sidebar/elements/sidebarHeader/SidebarHeader.svelte, packages/ui/src/lib/sidebar/elements/sidebarHint/SidebarHint.stories.svelte, packages/ui/src/lib/sidebar/elements/sidebarHint/SidebarHint.svelte, packages/ui/src/lib/sidebar/elements/sidebarHint/SidebarHintModal.svelte, packages/ui/src/lib/sidebar/sidebarUtils.ts, packages/ui/src/lib/tooltip/Tooltip.stories.svelte, packages/ui/src/lib/tooltip/Tooltip.svelte
addresses #269 #268 #267 
Also solves tabbed sidebar positioning when positioned left
**Why?**
User feedback highlighted issues
**How?**
Updates mainly to css and slots
#269 #268 #267 
no
storybook
storybook - more thorough usage documentation to follow
n/a
Y
=> Sidebar snags

.changeset/asd_ads_asd.md, packages/ui/src/lib/checkBox/Checkbox.stories.svelte, packages/ui/src/lib/checkBox/Checkbox.svelte, packages/ui/src/lib/checkBox/CheckboxGroup.svelte
Adds tooltips to Checkbox and CheckboxGroup.
**Why?**
Required where extra information is long or essential.
Storybook.
Storybook.
=> Update Checkbox & CheckboxGroup with tooltips

.changeset/josd-sadasda-sdasd.md, packages/maps/src/lib/mapControlGroup/MapControlGroup.stories.svelte, packages/maps/src/lib/mapControlGroup/MapControlGroup.svelte
Determine left/right/center alignment on contents of `MapControlGroup` based on whether it is positioned to the Left/Rght/Center:
This resolves https://github.com/Greater-London-Authority/ldn-viz-tools/issues/294
=> align contents of MapControlGroup depending on position

packages/ui/src/lib/button/Button.svelte, packages/ui/src/lib/checkBox/Checkbox.svelte, packages/ui/src/lib/checkBox/CheckboxGroup.stories.svelte, packages/ui/src/lib/checkBox/CheckboxGroup.svelte, packages/ui/src/lib/dataDownloadButton/DataDownloadButton.svelte, packages/ui/src/lib/geolocation/Geocoder.svelte, packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.stories.svelte, packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.svelte, packages/ui/src/lib/modal/Modal.svelte, packages/ui/src/lib/nonIdealState/NonIdealState.stories.svelte, packages/ui/src/lib/nonIdealState/NonIdealState.svelte, packages/ui/src/lib/placardButton/PlacardButton.svelte, packages/ui/src/lib/radioButton/RadioButton.stories.svelte, packages/ui/src/lib/radioButton/RadioButton.svelte, packages/ui/src/lib/radioButton/RadioButtonGroup.svelte, packages/ui/src/lib/radioButtonSolid/RadioButtonGroupSolid.svelte, packages/ui/src/lib/radioButtonSolid/RadioButtonSolid.stories.svelte, packages/ui/src/lib/radioButtonSolid/RadioButtonSolid.svelte, packages/ui/src/lib/spinners/Spinner.stories.svelte, packages/ui/src/lib/spinners/Spinner.svelte, packages/ui/src/lib/tabs/TabLabel.svelte, packages/ui/src/lib/tabs/TabList.svelte, packages/ui/src/lib/tabs/Tabs.stories.svelte, packages/ui/src/lib/tooltip/Tooltip.svelte
This adds docstrings that wil be added to the Storybook autodocs pages.
=> Improve docs

packages/ui/src/lib/select/Select.svelte
This adds some documentation for the `<Select>` component
=> [docs] Select docs

packages/ui/src/lib/sidebar/Sidebar.stories.svelte, packages/ui/src/lib/sidebar/Sidebar.svelte, packages/ui/src/lib/sidebar/elements/sidebarFooter/SidebarFooter.svelte, packages/ui/src/lib/sidebar/elements/sidebarHeader/SidebarHeader.svelte, packages/ui/src/lib/sidebar/elements/sidebarHint/SidebarHint.stories.svelte, packages/ui/src/lib/sidebar/elements/sidebarHint/SidebarHint.svelte, packages/ui/src/lib/sidebar/elements/sidebarSection/SidebarSection.svelte, packages/ui/src/lib/sidebar/elements/sidebarSection/sidebarGroupTitle/SidebarGroupTitle.svelte, packages/ui/src/lib/sidebar/elements/sidebarSection/sidebarSectionTitle/SidebarSectionTitle.stories.svelte, packages/ui/src/lib/sidebar/elements/sidebarSection/sidebarSectionTitle/SidebarSectionTitle.svelte, packages/ui/src/lib/sidebar/elements/sidebarTabs/SidebarTabLabel.svelte, packages/ui/src/lib/sidebar/elements/sidebarTabs/SidebarTabList.svelte, packages/ui/src/lib/sidebar/elements/sidebarTabs/SidebarTabs.stories.svelte, packages/ui/src/lib/sidebar/elements/sidebarToggle/SidebarToggle.svelte
This adds some initial docs for the sidebar.
=> [docs] add docs for sidebar

package-lock.json, packages/charts/src/lib/chartContainer/ChartContainer.svelte, packages/charts/src/lib/chartContainer/ExportBtns.svelte, packages/charts/src/lib/chartContainer/Footer.svelte, packages/charts/src/lib/chartContainer/SubTitle.svelte, packages/charts/src/lib/chartContainer/Title.svelte, packages/charts/src/lib/observablePlot/ObservablePlot.svelte, packages/charts/src/lib/observablePlotFragments/ObservablePlotFragments.stories.svelte, packages/charts/src/lib/observablePlotFragments/demo_data.js, packages/charts/src/lib/observablePlotFragments/observablePlotFragments.js, packages/charts/src/lib/scatterPlot/ScatterPlot.stories.svelte
=> Plot fragments

packages/maps/src/lib/mapControlLocationSearch/MapControlGeocoder.svelte, packages/maps/src/lib/mapControlLocationSearch/MapControlGeolocator.svelte, packages/maps/src/lib/mapControlLocationSearch/MapControlLocationSearch.svelte
Adds documentation to the map control components
=> Document map controls

apps/docs/.storybook/ciuStorybookTheme.ts, apps/docs/src/introduction/Introdution.mdx
This creates a homepage that gives an overview of all packages (rather than just `ui`).
=> create an initial Storybook homepage that gives overview of all packages

packages/maps/src/lib/mapControlFullscreen/MapControlFullscreen.stories.svelte, packages/maps/src/lib/mapControlGroup/MapControlGroup.stories.svelte, packages/maps/src/lib/mapControlLocationSearch/MapControlLocationSearch.stories.svelte, packages/maps/src/lib/mapControlPan/MapControlPan.stories.svelte, packages/maps/src/lib/mapControlRefresh/MapControlRefresh.stories.svelte, packages/maps/src/lib/mapControlZoom/MapControlZoom.stories.svelte
This groups together the stories for the different map control components into one directory in the sidebar of the Storybook site:
=> group map control component stories together

.changeset/sfsd-fsdfsd-fdfs.md, packages/ui/src/lib/checkBox/Checkbox.svelte, packages/ui/src/lib/index.ts, packages/ui/src/lib/switch/Switch.stories.svelte, packages/ui/src/lib/switch/Switch.svelte
=> add Switch component

.changeset/nsfn-fsfs-sdsd.md, packages/ui/src/lib/index.ts, packages/ui/src/lib/modal/Modal.svelte, packages/ui/src/lib/popover/CloseIcon.svelte, packages/ui/src/lib/popover/Popover.stories.svelte, packages/ui/src/lib/popover/Popover.svelte, packages/ui/src/lib/sidebar/elements/sidebarHint/SidebarHint.stories.svelte, packages/ui/src/lib/sidebar/elements/sidebarHint/SidebarHint.svelte, packages/ui/src/lib/tooltip/Tooltip.svelte
This adds a new `Popover` component.
No.
=> initial commit of Popover component

.changeset/fix-geolocator-ui.md, packages/ui/src/lib/geolocation/Geolocator.svelte, packages/ui/src/lib/geolocation/TargetIcon.svelte
Fixes geolocation search on mobile devices.
**Why?**
It's broken.
On mobile devices.
=> Fix geolocation permissions on mobile

.changeset/geocoder-z-index.md, packages/ui/src/lib/geolocation/GeocoderSuggestionList.svelte
Increase z-index on geolocation suggestions so it sits above the sidebar.
=> Increase z-index of geolocation suggestions

.changeset/asd-sdasd-gdfge.md, packages/ui/src/lib/checkBox/CheckboxGroup.stories.svelte, packages/ui/src/lib/checkBox/CheckboxGroup.svelte
updated visual appearance of `CheckboxGroup` component when bound `selectedOptions` prop is externally updated
=> update appearance of checkbox group when selectedOptions externally updated

.changeset/tables-color.md, packages/tables/src/lib/table/menus/PopoverMenu.svelte
This changes the color of text in table popover menus so they are usable in dark mode.
=> Table popover menus

.changeset/wide-tables.md, packages/tables/src/lib/table/Table.stories.svelte, packages/tables/src/lib/table/Table.svelte, packages/tables/src/lib/table/rows/ColumnGroupHeadingRow.svelte, packages/tables/src/lib/table/rows/ColumnHeadingRow.svelte, packages/tables/src/lib/table/rows/ColumnSummariesRow.svelte, packages/tables/src/lib/table/rows/ControlRow.svelte, packages/tables/src/lib/table/rows/DataRow.svelte, packages/tables/src/lib/table/rows/GroupHeadingRow.svelte, packages/tables/src/lib/table/rows/GroupRowCombined.svelte, packages/tables/src/lib/table/rows/GroupSummaryRow.svelte
Fix the rendering of wide tables
=> Fix rendering of wide tables

.changeset/update-switch.md, packages/ui/src/lib/switch/Switch.stories.svelte, packages/ui/src/lib/switch/Switch.svelte
Updates the `Switch` component to add `size` and `labelOn` props.
See https://github.com/Greater-London-Authority/ldn-viz-tools/issues/373
=> add size and labelOn props to switch

.changeset/dsfsdf-dfdsf-adasd.md, packages/maps/src/lib/index.js, packages/maps/src/lib/mapControlBorough/MapControlBorough.stories.svelte, packages/maps/src/lib/mapControlBorough/MapControlBorough.svelte, packages/maps/src/lib/mapControlBorough/boroughs.json
This adds a map component that zooms to a borough selected from a select box.
=> Borough map control

.changeset/radio-button-tooltips.svelte, packages/ui/src/lib/radioButton/RadioButton.svelte, packages/ui/src/lib/radioButton/RadioButtonGroup.stories.svelte, packages/ui/src/lib/radioButton/RadioButtonGroup.svelte
This allows radio buttons to havve tooltips (just like checkboxes).
=> Radio button hints

packages/tables/src/lib/core/renderers/GoodOrBad.stories.svelte
This adds more stories for the 3 different values of the `goodIs` prop, to show the appearance of the component in more cases.
=> more stories for GoodOrBad, for different cases of goodIs prop

apps/docs/.storybook/ciuStorybookTheme.ts
minor tweak to storybook theme
=> adjust secondary ui color of storybook theme

.changeset/reactive-borough-context.md, packages/maps/src/lib/mapContextLayers/boroughsContextLayer/BoroughsContextLayer.svelte
Makes borough context layer stories reactive
**Why?**
So you can tweak fill and line settings in the story.
Addresses: #364 
Storybook.
=> Make boroughs context layer reactive

packages/charts/src/lib/chartContainer/ExportBtns.svelte, packages/ui/src/lib/appShell/AppShell.stories.svelte, packages/ui/src/lib/button/AsyncButton.stories.svelte, packages/ui/src/lib/button/Button.stories.svelte, packages/ui/src/lib/copyButton/CopyButton.stories.svelte, packages/ui/src/lib/copyButton/CopyButton.svelte, packages/ui/src/lib/dataDownloadButton/DataDownloadButton.stories.svelte, packages/ui/src/lib/forms/elements/formSubmitButton/FormSubmitButton.stories.svelte, packages/ui/src/lib/geolocation/Geocoder.svelte, packages/ui/src/lib/geolocation/Geolocator.svelte, packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.stories.svelte, packages/ui/src/lib/popover/Popover.svelte, packages/ui/src/lib/sidebar/Sidebar.stories.svelte, packages/ui/src/lib/sidebar/elements/sidebarTabs/SidebarTabs.stories.svelte, packages/ui/src/lib/tabs/Tabs.stories.svelte, packages/ui/src/lib/toaster/Toast.svelte
Applies (more) consistent theming and sizing to icons
=> Make icon sizing more consistent

packages/themes/tokens/design-tokens.tokens.json, packages/ui/src/lib/switch/Switch.stories.svelte, packages/ui/src/lib/toaster/Toast.svelte, packages/ui/src/lib/toaster/Toaster.stories.svelte
adjusts color of switch component
=> Switch colors

.changeset/chilled-kangaroos-film.md, packages/ui/src/lib/input/Input.svelte
fixes color of input text when disabled
**Why?**
it was incorrect before
**How?**
adjust prop and add color classes
#370 
no
sb
na
yes
=> Fix input text color

packages/charts/.eslintrc.cjs, packages/charts/src/lib/observablePlot/ObservablePlot.stories.svelte, packages/charts/src/lib/observablePlot/ObservablePlot.svelte
This resolves some linter warnings in the charts package.
=> lint charts package

packages/tables/.eslintrc.cjs, packages/tables/src/lib/core/aggregateRenderers/StackedBar.svelte, packages/tables/src/lib/core/lib/dataFns.test.js, packages/tables/src/lib/core/lib/dataObject.test.js, packages/tables/src/lib/table/Table.svelte, packages/tables/src/lib/table/rows/GroupHeadingRow.svelte, packages/tables/src/lib/table/rows/GroupRowCombined.svelte, packages/tables/src/lib/table/rows/Scaffolding.svelte
This resolves some linter warnings for the `tables` package.
=> lint tables package

.changeset/sfsf-sdfsdf-sdfdsf.md, packages/ui/src/lib/dataDownloadButton/DataDownloadButton.stories.svelte, packages/ui/src/lib/dataDownloadButton/DataDownloadButton.svelte, packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.stories.svelte, packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.svelte, packages/ui/src/lib/index.ts, packages/ui/src/lib/multipleActionButton/MultipleActionButton.stories.svelte, packages/ui/src/lib/multipleActionButton/MultipleActionButton.svelte
This adds a `MultipleActionButton` that combines a button and popover menu, so that the user can select which action
(or variation on an action) will be performed when the button is pressed.
**Why?**
**How?**
=> Multiple action buttons

.changeset/dadasd-fsdfsf-ada.md, .changeset/tender-rocks-tell.md, apps/docs/.storybook/withThemeByClassNameStore.ts, packages/charts/src/lib/chartContainer/ChartContainer.stories.svelte, packages/charts/src/lib/chartContainer/ChartContainer.svelte, packages/charts/src/lib/chartContainer/ExportBtns.svelte, packages/charts/src/lib/chartContainer/Footer.svelte, packages/charts/src/lib/observablePlot/ObservablePlot.stories.svelte, packages/charts/src/lib/observablePlot/ObservablePlot.svelte, packages/charts/src/lib/observablePlotFragments/observablePlotFragments.ts, packages/ui/src/lib/button/Button.stories.svelte, packages/ui/src/lib/button/Button.svelte, packages/ui/src/lib/dataDownloadButton/DataDownloadButton.svelte, packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.svelte, packages/ui/src/lib/multipleActionButton/MultipleActionButton.stories.svelte, packages/ui/src/lib/multipleActionButton/MultipleActionButton.svelte, packages/ui/src/lib/sidebar/elements/sidebarTabs/SidebarTabLabel.svelte, packages/ui/src/lib/sidebar/elements/sidebarTabs/SidebarTabs.stories.svelte
=> Chart snags

.changeset/fix-ts-mapthemes.md, packages/maps/src/lib/themes/bounds.test.ts, packages/maps/src/lib/themes/bounds.ts
Fix TypeScript for themes package within thee maps package.
=> Fix types in map themes package

.changeset/fix-ts-fullscreen.md, packages/maps/src/lib/mapControlFullscreen/MapControlFullscreen.stories.svelte, packages/maps/src/lib/mapControlFullscreen/MapControlFullscreen.svelte
Fix TypeScript for `MapControlFullscreen`.
=> Fix map control fullscreen types

.changeset/fix-ts-borough.md, packages/maps/src/lib/mapControlBorough/MapControlBorough.svelte, packages/maps/tsconfig.json
Fix TypeScript for `MapControlBorough`.
=> Fix types in map control borough

.changeset/multi-action-button-props.md, packages/charts/src/lib/chartContainer/ExportBtns.svelte, packages/ui/src/lib/dataDownloadButton/DataDownloadButton.stories.svelte, packages/ui/src/lib/dataDownloadButton/DataDownloadButton.svelte, packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.stories.svelte, packages/ui/src/lib/imageDownloadButton/ImageDownloadButton.svelte
=> Remove uses of default slot on MultiActionButton

.changeset/table-capitalization.md, README.md, packages/tables/src/lib/core/renderers/Header.svelte, packages/tables/src/lib/table/rows/ColumnGroupHeadingRow.svelte
Remove capitalization class from header cells in Tables.
=> Table capitalization

.changeset/tab-list-highligting.md, packages/ui/src/lib/sidebar/Sidebar.stories.svelte, packages/ui/src/lib/sidebar/elements/sidebarTabs/SidebarTabList.svelte, packages/ui/src/lib/tabs/TabList.svelte
Update highlighting of tab icons inside a `TabList` or `SidebarTabList` when the selected item is changed externally
=> update tab highlighting when selected tab externally changed

.changeset/table-chart-api.md, packages/tables/src/lib/table/Table.svelte, packages/tables/src/lib/table/TableContainer.svelte
Updates the table container component to align with the API of the chart container
=> TABLES: updates table container to align with the API of the chart container

packages/tables/src/lib/core/lib/computeWidths.ts, packages/tables/src/lib/table/Table.stories.svelte, packages/tables/src/lib/table/TableColWidths.stories.svelte, packages/tables/src/lib/table/TableComplex.stories.svelte, packages/tables/src/lib/table/TableHSDS.stories.svelte, packages/tables/src/lib/table/TableHeader.stories.svelte, packages/tables/src/lib/table/rows/Scaffolding.svelte, packages/tables/src/lib/table/rows/headerRows/ColumnHeadingRow.svelte, packages/tables/src/lib/table/rows/headerRows/ColumnSummariesRow.svelte, packages/tables/src/lib/table/rows/headerRows/ControlRow.svelte
=> Internal improvements to Table

.changeset/table-changes.md, packages/tables/src/lib/core/renderers/BarCell.svelte, packages/tables/src/lib/core/renderers/BarDivergingAxis.svelte, packages/tables/src/lib/core/renderers/BarDivergingCell.svelte, packages/tables/src/lib/core/renderers/CategoricalTick.svelte, packages/tables/src/lib/core/renderers/ColorAndLabel.svelte, packages/tables/src/lib/core/renderers/ColoredCell.svelte, packages/tables/src/lib/core/renderers/DateCell.svelte, packages/tables/src/lib/core/renderers/GoodOrBad.svelte, packages/tables/src/lib/core/renderers/Header.svelte, packages/tables/src/lib/core/renderers/PairArrowAxis.svelte, packages/tables/src/lib/core/renderers/PairArrowCell.svelte, packages/tables/src/lib/core/renderers/TextCell.svelte, packages/tables/src/lib/core/renderers/TextCellWithUncertainty.svelte, packages/tables/src/lib/table/Table.stories.svelte, packages/tables/src/lib/table/TableComplex.stories.svelte, packages/tables/src/lib/table/TableHeader.stories.svelte, packages/tables/src/lib/table/TableHeader.svelte, packages/tables/src/lib/table/menus/FilterMenu.svelte, packages/tables/src/lib/table/rows/DataRow.svelte, packages/tables/src/lib/table/rows/RowRenderer.svelte, packages/tables/src/lib/table/rows/Scaffolding.svelte, packages/tables/src/lib/table/rows/headerRows/ColumnGroupHeadingRow.svelte, packages/tables/src/lib/table/rows/headerRows/ColumnGroupHeadingRuleRow.svelte, packages/tables/src/lib/table/rows/headerRows/ColumnHeadingRow.svelte, packages/tables/src/lib/table/rows/headerRows/ColumnSummariesRow.svelte, packages/tables/src/lib/table/rows/headerRows/ControlRow.svelte
Squashes console warnings,
Minimises some type errors,
Addresses styling issues,
=> Table refactor

.changeset/chart-control-slot.md, packages/charts/src/lib/chartContainer/ChartContainer.stories.svelte, packages/charts/src/lib/chartContainer/ChartContainer.svelte
https://dev.ldn-gis.co.uk/storybook-chart-container-controls-slot/?path=/story/charts-chartcontainer--with-title-subtitle-and-controls
=> Chart container controls slot

.changeset/sidebar-control.svelte, packages/ui/src/lib/appShell/AppShell.stories.svelte, packages/ui/src/lib/appShell/AppShell.svelte
Demo: https://dev.ldn-gis.co.uk/storybook-externally-control-sidebar/?path=/story/app-appshell--external-opening-closing-of-sidebar
=> allow sidebar to be externally opened or closed

.changeset/strange-wombats-watch.md, packages/charts/src/lib/observablePlot/ObservablePlotInner.stories.svelte, packages/charts/src/lib/observablePlot/ObservablePlotInner.svelte
Fix for chart width 
**Why?**
broken in recent update 
**How?**
retrigger render using key
- [x ] Have you included changeset file?
=> Update ObservablePlot width when width of parent changes

.changeset/slow-weeks-explode.md, package-lock.json, packages/charts/src/lib/chartContainer/ChartContainer.stories.svelte, packages/charts/src/lib/chartContainer/ExportBtns.svelte, packages/charts/src/lib/chartContainer/Footer.svelte
Changes the alignment of the byline/source and export buttons. Also fixes console errors.
**Why?**
Because of misalignment. 
**How?**
class updates
#636 
No
Storybook
Storybook
NA
Yes
=> Chart footer

.changeset/forty-rockets-retire.md, package-lock.json, packages/charts/src/lib/observablePlot/ObservablePlotInner.svelte
My previous PR changed the contents of `addEventHandlerInner` to an earlier version which broke functionality of some charts.
I've added the new functionality back in so that it checks for mark values if the relevant channels exist but ignores them if not.
=> Fix event handler

.changeset/deck-overlay.md, packages/maps/package.json, packages/maps/src/lib/index.js, packages/maps/src/lib/mapDeckOverlay/MapDeckOverlay.stories.svelte, packages/maps/src/lib/mapDeckOverlay/MapDeckOverlay.svelte
Preview: https://dev.ldn-gis.co.uk/storybook-deck-overlay/?path=/docs/maps-mapdeckoverlay--documentation
=> add MapDeckOverlay component

.changeset/layer-control-group.md, packages/ui/src/lib/index.ts, packages/ui/src/lib/layerControl/LayerContolGroup.stories.svelte, packages/ui/src/lib/layerControl/LayerControl.svelte, packages/ui/src/lib/layerControl/LayerControlGroup.svelte
Preview: https://dev.ldn-gis.co.uk/storybook-layer-control-group/?path=/docs/ui-layercontrolgroup--documentation
=> add LayerControlGroup component

.changeset/callout.md, packages/ui/src/lib/callout/Callout.stories.svelte, packages/ui/src/lib/callout/Callout.svelte, packages/ui/src/lib/index.ts
This adds the `Callout` component from the hsds-hub project
**Why?**
There is a need for a similar component in the LBSM project, and it is likely to also be needed in other future projects.
=> Add Callout component

.changeset/a11y-lint.md, packages/tables/src/lib/table/rows/groupRows/GroupHeadingRow.svelte, packages/tables/src/lib/table/rows/groupRows/GroupRowCombined.svelte, packages/tables/src/lib/table/rows/headerRows/ControlRow.svelte, packages/ui/src/lib/layerControl/ColorPicker.svelte
Use `<button>` element rather than `<div>` for some clickable elements
=> replace some clickable divs with buttons (fix #705)

packages/tables/src/lib/core/renderers/BarCell.svelte, packages/tables/src/lib/core/renderers/CategoricalTick.svelte
=> resolve some unexpected prop warnings

packages/ui/src/lib/sidebar/Sidebar.svelte
Document the fact that sidebar state should be persisted to a store.
=> add comment about persisting sidebar state (fix #390)

.changeset/color-legend-reversible.md, packages/ui/src/lib/colorLegends/ColorLegend.stories.svelte, packages/ui/src/lib/colorLegends/ColorLegend.svelte
Preview: https://github.com/Greater-London-Authority/ldn-viz-tools/pull/734
=> allow direction of color legends to be flipped (fix #236)

.changeset/cyan-tips-tease.md, packages/themes/.gitignore, packages/themes/build.js, packages/themes/config.json, packages/themes/tokens/design-tokens.tokens.json
Adds a new build step to transform style dictionary docs into a format that allows more documentation (specifically for our content site)
**Why?**
required for documentation
**How?**
new build step in style dictionary config
no
storybook
existing docs in confluence
y
y
=> Design token docs

.changeset/late-shrimps-yell.md, packages/ui/src/lib/layerControl/ColorPicker.svelte
Changes the colour chip on layer control from square to rounded.
**Why?**
Because it looks better
**How?**
by applying, rounded-full class.
n/a
no
storybook
n/a
n/a
yes
=> Layer control change (rounded color chip)

README.md
Added steps to set-up and contribute to vis tools on readme.
**Why?**
Documenting a process
**How?**
Updated readme 
NA
No
NA 
readme
NA
Yes
=> Added step-by-step instructions to the readme

apps/docs/.storybook/preview.ts, packages/ui/src/lib/sidebar/Sidebar.stories.svelte, packages/ui/src/lib/sidebar/elements/sidebarFooter/SidebarFooter.stories.svelte, packages/ui/src/lib/themeSwitcher/ThemeSwitcher.svelte
updates the theme switch to be the same as the implementation in the content site
**Why?**
Theme switching requires a ui
**How?**
#463
no
sb and content site
sb - more detailed docs pending as part of 'docs site'
yes
=> Theme switch trigger

.changeset/sidebar-from-array.md, packages/ui/src/lib/index.ts, packages/ui/src/lib/sidebar/SidebarFromArray.stories.svelte, packages/ui/src/lib/sidebar/SidebarFromArray.svelte
This adds a `SidebarFromArray` component that allows the creation of a tabbed sidebar from a list of tabs.
=> add SidebarFromArray component

packages/ui/src/lib/forms/CustomInput.svelte
address annoying warning in build action
=> comment out type from example custom component

.changeset/fair-geese-retire.md, package-lock.json, packages/ui/src/lib/modal/Modal.stories.svelte, packages/ui/src/lib/modal/Modal.svelte
To improve accessibility and bring the Modal in line with best practice and the design system:
- Updated `openFocus` to `$description.id` and added aria-labelledby attribute to that element so screen reader can access and dictate content of the Modal
- `description` is now an essential prop
- Added `buttons` slot to Modal to allow for proper styling (to match Figma) and moved it outside of the description/content div so the right-hand side is always inline with the close button
- Fixed styling in Modal component and stories to match Figma ~(except in the case where the contents overflow and a scrollbar is created, which needs further attention)~
**Related issues**: #831 #750 
No
Storybook
**How is …
=> Ally modal

packages/ui/src/lib/radioButtonSolid/RadioButtonSolid.stories.svelte
Fix for a11y error caused in story where duplicate ids present
**Why?**
**How?**
#753
=> fix duplicate id issue

.changeset/multiple-action-z-index.md, packages/ui/src/lib/multipleActionButton/MultipleActionButton.stories.svelte, packages/ui/src/lib/multipleActionButton/MultipleActionButton.svelte
This fixes https://github.com/Greater-London-Authority/ldn-viz-tools/issues/869
=> fix z-index of MultipleActionButton

.npmrc, apps/docs/.storybook/ciuStorybookTheme.ts, apps/docs/.storybook/main.ts, apps/docs/.storybook/manager.js, apps/docs/.storybook/withThemeByClassName.ts, apps/docs/package.json, apps/docs/src/introduction/Introdution.mdx, package-lock.json, package.json, packages/charts/src/lib/Introduction.mdx, packages/maps/src/lib/Introduction.mdx, packages/tables/src/lib/introduction.mdx, packages/ui/src/lib/Introduction.mdx, packages/ui/src/lib/theme/Theme.mdx, packages/ui/src/lib/userPreference/Documentation.mdx
upgrade storybook and implement any breaking changes to current setup
=> update to storybook 9

packages/ui/src/lib/callout/Callout.svelte, packages/ui/src/lib/copyButton/CopyButton.stories.svelte, packages/ui/src/lib/copyButton/CopyButton.svelte
=> Copy button

.changeset/tables-header-customization.md, packages/tables/src/lib/core/lib/dataObj.ts, packages/tables/src/lib/core/lib/types.ts, packages/tables/src/lib/core/renderers/Header.svelte, packages/tables/src/lib/table/Table.stories.svelte, packages/tables/src/lib/table/Table.svelte, packages/tables/src/lib/table/TableHeader.svelte, packages/tables/src/lib/table/rows/headerRows/ColumnGroupHeadingRow.svelte, packages/tables/src/lib/table/rows/headerRows/ColumnHeadingRow.svelte
Preview of story with no header: https://dev.ldn-gis.co.uk/storybook-table-header-customization/?path=/story/tables-components-table--no-header
Preview of story with coloured header and no rules: https://dev.ldn-gis.co.uk/storybook-table-header-customization/?path=/story/tables-components-table--coloured-headers
=> Allow more customization of table headers

packages/ui/src/lib/select/Select.svelte
Adds missing interaction styles on select component
=> Sv5 select styles

.vscode/settings.json, apps/docs/svelte.config.js, packages/ui/src/app.d.ts, packages/ui/src/lib/analytics/AnalyticsAndCookieConsent.mdx, packages/ui/src/lib/analytics/AnalyticsAndCookieConsent.svelte, packages/ui/src/lib/analytics/CookieControlSettings.stories.svelte, packages/ui/src/lib/analytics/CookieControlSettings.svelte, packages/ui/src/lib/index.ts, packages/ui/svelte.config.js
Adds Analytics and cookie consent
=> Sv5 analytics

packages/ui/src/lib/analytics/PrivacyPolicyLink.svelte, packages/ui/src/lib/footer/Footer.stories.svelte, packages/ui/src/lib/footer/Footer.svelte, packages/ui/src/lib/footer/FooterCookieMenu.svelte, packages/ui/src/lib/index.ts, packages/ui/src/lib/layoutExamples/Dashboards/LeggiExplorer.svelte, packages/ui/src/lib/sidebar/elements/sidebarFooter/SidebarFooter.stories.svelte
adds a first pass footer component
=> Sv5 basic footer

.changeset/sixty-plums-jump.md
added changeset to allow release of sv5 theme update
=> Sv5 theme changeset
